import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
fs.mkdirSync('.preview-build',{recursive:true});
fs.writeFileSync('.preview-build/question-service.mjs',ts.transpileModule(fs.readFileSync('server/question-service.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {questionsApi}=await import('../.preview-build/question-service.mjs');
const sql=new DatabaseSync(':memory:');
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(`drizzle/${f}`,'utf8'));
const DB={prepare(query){let args=[];return {bind(...values){args=values;return this;},async all(){return {results:sql.prepare(query).all(...args)};},async first(){return sql.prepare(query).get(...args)||null;},async run(){const result=sql.prepare(query).run(...args);return {meta:{changes:Number(result.changes)}};}};},async batch(items){sql.exec('BEGIN');try{const result=[];for(const item of items)result.push(await item.all());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const env={DB,RATE_LIMIT_SALT:'test-salt',OPENAI_API_KEY:'test-key',ALLOWED_ORIGIN:'https://example.com'};
const tasks=[];const ctx={waitUntil(p){tasks.push(p);}};
const body={id:crypto.randomUUID(),passage:'마가복음 4장',content:'예수님은 왜 비유로 말씀하셨나요?',name:'익명'};
const post=(data=body,origin='https://example.com')=>new Request('https://api.example.com/api/questions',{method:'POST',headers:{origin,'Content-Type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify(data)});
let calls=0;
globalThis.fetch=async()=>{calls++;return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'예수님이 비유로 말씀하신 이유는 무엇인가요?'}]}]});};
assert.equal((await questionsApi(post({...body,content:'짧음'}),env,ctx)).status,400);
assert.equal((await questionsApi(post(body,'https://evil.example'),env,ctx)).status,403);
assert.equal((await questionsApi(post(),env,ctx)).status,201);
await Promise.all(tasks);
let list=await (await questionsApi(new Request('https://api.example.com/api/questions'),env)).json();
assert.equal(list.questions[0].summaryStatus,'ready');assert.equal(list.questions[0].content,body.content);
assert.equal((await questionsApi(post(),env,ctx)).status,200);assert.equal(calls,1);
assert.equal((await questionsApi(post({...body,content:'다른 질문을 보냅니다.'}),env,ctx)).status,409);
globalThis.fetch=async()=>Response.json({error:{}},{status:429});
const failed={...body,id:crypto.randomUUID()};
assert.equal((await questionsApi(post(failed),env,ctx)).status,201);await Promise.all(tasks);
assert.equal(sql.prepare('SELECT summary_status FROM questions WHERE id=?').get(failed.id).summary_status,'failed');
assert.equal(sql.prepare('SELECT content FROM questions WHERE id=?').get(failed.id).content,failed.content);
for(let i=0;i<18;i++)assert.equal((await questionsApi(post({...body,id:crypto.randomUUID()}),{...env,OPENAI_API_KEY:undefined},ctx)).status,201);
assert.equal((await questionsApi(post({...body,id:crypto.randomUUID()}),env,ctx)).status,429);
assert.equal((await questionsApi(post({...body,id:crypto.randomUUID()}),{...env,RATE_LIMIT_SALT:undefined},ctx)).status,503);
sql.close();console.log('Passed: validation, origin restriction, persistence, AI summary, idempotent retry, failure preservation, rate limit, missing configuration.');
