"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { BookOpen, Plus, Sparkles, ChevronDown, ArrowRight, Check, MessageCircle, X, Send, CalendarDays } from "lucide-react";
import ReadingSchedule from "../components/reading-schedule";
import {questionEndpoint} from "../lib/api-client";
import AdminPanel from "../components/admin-panel";
import {comparePassages} from "../lib/question-order";
type Question = { reviewedAt?:number|null; id:string; passage:string; content:string; name:string; summary:string|null; summaryStatus?:string; createdAt:number; example?:boolean };
const examples:Question[] = [
 {id:"example-1",passage:"창세기 1:26–27",name:"익명",content:"하나님께서 사람을 만드실 때 ‘우리의 형상을 따라’라고 말씀하시는데, 여기서 ‘우리’는 누구를 가리키는 건가요? 또 하나님의 형상을 닮았다는 것은 외모가 비슷하다는 뜻인지, 다른 의미가 있는지 궁금합니다.",summary:"‘우리의 형상’에서 ‘우리’는 누구이며, 하나님의 형상은 무엇을 뜻하나요?",createdAt:0,example:true},
 {id:"example-2",passage:"창세기 2:2–3",name:"김은혜",content:"하나님은 피곤하지 않으실 텐데 일곱째 날에 쉬셨다고 하네요. 이 쉼은 어떤 의미인가요? 우리가 안식일을 지키는 것과도 연결되는지 알고 싶어요.",summary:"하나님이 일곱째 날에 쉬신 이유와 안식의 의미는 무엇인가요?",createdAt:0,example:true},
 {id:"example-3",passage:"창세기 3:1–7",name:"익명",content:"선악을 알게 하는 나무를 처음부터 만들지 않으셨으면 사람이 죄를 짓지 않았을 것 같아요. 하나님은 왜 그 나무를 에덴동산에 두셨을까요?",summary:"하나님은 왜 에덴동산에 선악을 알게 하는 나무를 두셨나요?",createdAt:0,example:true},
];
export default function Home(){
 const [questions,setQuestions]=useState<Question[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[tab,setTab]=useState("summary"),[open,setOpen]=useState(false),[sending,setSending]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[passage,setPassage]=useState(""),[name,setName]=useState(""),[content,setContent]=useState("");
 const [demo,setDemo]=useState(false),[aiEnabled,setAiEnabled]=useState(false);
 const requestId=useRef<{id:string;body:string}|null>(null);
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 async function load(quiet=false){if(!quiet)setLoading(true);try{const res=await fetch(questionEndpoint());if(!res.ok)throw new Error();const data=await res.json() as {questions:Question[];demo?:boolean;aiEnabled?:boolean};setQuestions(data.questions);setDemo(Boolean(data.demo));setAiEnabled(Boolean(data.aiEnabled));setLoadError(false);}catch{setLoadError(true);}finally{if(!quiet)setLoading(false);}}
 useEffect(()=>{const refresh=()=>void load(true);window.addEventListener("questions-updated",refresh);return()=>window.removeEventListener("questions-updated",refresh);},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(true),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!questions.some(q=>q.summaryStatus==="pending"&&Date.now()-q.createdAt<120000))return;const timer=setInterval(()=>void load(true),3000);return()=>clearInterval(timer);},[questions]);
 useEffect(()=>{if(open){dialog.current?.showModal();document.body.style.overflow="hidden";}else{dialog.current?.close();document.body.style.overflow="";}return()=>{document.body.style.overflow="";};},[open]);
 function close(){if(sending)return;setOpen(false);trigger.current?.focus();}
 async function submit(e:FormEvent){e.preventDefault();setError("");setSending(true);try{const body=JSON.stringify({passage,name,content});if(requestId.current?.body!==body)requestId.current={id:crypto.randomUUID(),body};const res=await fetch(questionEndpoint(),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:requestId.current.id,passage,name,content})});const data=await res.json() as {question:Question;error?:string};if(!res.ok)throw new Error(data.error||"질문을 저장하지 못했습니다.");setQuestions(q=>[data.question,...q.filter(item=>item.id!==data.question.id)]);setLoadError(false);setContent("");setPassage("");setName("");setOpen(false);setNotice("질문이 등록되었습니다. 다음 모임에서 함께 나눠요.");trigger.current?.focus();}catch(e){setError(e instanceof Error?e.message:"연결을 확인하고 다시 시도해주세요.");}finally{setSending(false);}}
 const [page,setPage]=useState(1),[order,setOrder]=useState('recent');
 useEffect(()=>{const read=()=>{const params=new URLSearchParams(location.search);setPage(Math.max(1,Math.floor(Number(params.get('page')))||1));setOrder(params.get('sort')==='passage'?'passage':'recent');};read();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read);},[]);
 const list=[...(demo?examples:questions)].sort(order==='passage'?comparePassages:(a,b)=>b.createdAt-a.createdAt||a.id.localeCompare(b.id));
 const pages=Math.max(1,Math.ceil(list.length/10)),activePage=Math.min(page,pages),visible=list.slice((activePage-1)*10,activePage*10);
 function navigate(next:number,sort=order){setPage(next);setOrder(sort);const url=new URL(location.href);url.searchParams.set('page',String(next));url.searchParams.set('sort',sort);history.pushState(null,'',url);}

 return <><header className="site-header"><div className="header-inner"><a href="#" className="brand" aria-label="여의도침례교회 목요성경통독 홈"><span className="brand-icon"><img src="./church-mark.png" alt="목요일 성경통독 마크" width={64} height={64}/></span><span>여의도침례교회 목요성경통독<small>정진형 목사</small></span></a><span className="header-note">함께 읽고, 깊이 이해하는 시간</span><span className="edition">THURSDAY BIBLE READING</span></div></header>
 <main><div className="page-top"><div><div className="eyebrow">말씀을 읽다가, 궁금해졌나요?</div><h1>우리의 질문이<br className="mobile-break"/> 깊어지는 시간<span>.</span></h1><p className="intro">읽다가 멈춘 그 구절, 여기에 남겨주세요.<br className="mobile-break"/> 다음 모임에서 함께 나눕니다.</p></div><button ref={trigger} className="primary compose" onClick={()=>{setError("");setOpen(true);}}><Plus size={20}/>질문 남기기</button></div>
 <ReadingSchedule/>
 <div className="workspace"><section className="board" aria-label="질문 게시판"><div className="board-heading"><h2>함께 나누는 질문 <span>{list.length}</span></h2><select className="sort-select" aria-label="질문 정렬" value={order} onChange={e=>navigate(1,e.target.value)}><option value="recent">최근 등록순</option><option value="passage">본문순</option></select></div><div className="tabs" role="tablist" aria-label="질문 보기 방식"><button id="summary-tab" role="tab" aria-selected={tab==="summary"} aria-controls="questions-panel" onClick={()=>setTab("summary")} className={tab==="summary"?"active":""}><Sparkles size={17}/>핵심 질문</button><button id="original-tab" role="tab" aria-selected={tab==="original"} aria-controls="questions-panel" onClick={()=>setTab("original")} className={tab==="original"?"active":""}><MessageCircle size={17}/>질문 원문</button></div><div className="board-hint"><Sparkles size={16}/><p>{demo?"아래 질문과 AI 요약은 화면 구성을 위한 예시입니다.":aiEnabled?"AI가 질문의 핵심을 정리합니다. 펼치면 원문을 볼 수 있어요.":"등록한 질문은 원문으로 표시됩니다. AI 요약 연결을 준비 중입니다."}</p></div>
 {notice&&<div className="notice" role="status"><Check size={18}/>{notice}<button aria-label="알림 닫기" onClick={()=>setNotice("")}><X size={16}/></button></div>}{loadError&&<div className="load-error" role="alert">최신 질문을 불러오지 못했습니다. <button onClick={()=>void load()}>다시 불러오기</button></div>}
 <div id="questions-panel" role="tabpanel" aria-labelledby={tab==="summary"?"summary-tab":"original-tab"} aria-busy={loading}>{loading?<div className="loading">질문을 불러오고 있어요…</div>:!list.length?<div className="loading">아직 등록된 질문이 없습니다.<br/>첫 번째 질문을 남겨주세요.</div>:visible.map((q,i)=><details className="question" key={q.id}><summary><span className="question-no">{String(list.length-(activePage-1)*10-i).padStart(2,"0")}</span><span className="question-body"><span className="question-top"><span className="passage"><BookOpen size={14}/>{q.passage}</span><span className="status">{q.example?"예시 질문":"접수 완료"}</span></span><span className="question-title">{tab==="summary"?(q.summary||q.content):q.content}</span><span className="question-meta">{q.name}<span>·</span>{q.example?"예시":new Date(q.createdAt).toLocaleDateString("ko-KR")}{tab==="summary"&&q.summary&&<span className="ai-label"><Sparkles size={12}/>{q.example?"AI 요약 예시":"AI 요약"}</span>}{!q.example&&!q.summary&&<span className="summary-status">{q.summaryStatus==="pending"&&Date.now()-q.createdAt<120000?"AI 요약 중…":"원문 표시"}</span>}</span>{q.reviewedAt&&<span className="reviewed-note">인도자가 확인했습니다.</span>}</span><ChevronDown size={19} className="expand"/></summary><div className="question-original"><strong>작성한 질문 원문</strong><p>{q.content}</p><span>이 질문은 모임에서 함께 나눌 예정입니다.</span></div></details>)}</div><nav className="pagination" aria-label="질문 페이지"><button disabled={activePage===1} onClick={()=>navigate(activePage-1)}>이전</button><span>{activePage} / {pages} 페이지</span><button disabled={activePage===pages} onClick={()=>navigate(activePage+1)}>다음</button></nav><div className="board-end"><span/>작은 궁금증도 좋은 질문이 됩니다<span/></div></section>
 <aside><section className="guide"><span className="guide-icon"><MessageCircle size={23}/></span><h2>질문은 편하게, <br/>나눔은 더 깊게.</h2><p>어려운 질문이 아니어도 괜찮아요. 나눔이 말씀을 더 풍성하게 합니다.</p><ol><li><span>01</span><div><strong>읽은 본문을 적어주세요</strong><p>성경 이름과 장·절을 함께 남겨주세요.</p></div></li><li><span>02</span><div><strong>이름 없이도 괜찮아요</strong><p>로그인 없이 익명으로 질문할 수 있어요.</p></div></li><li><span>03</span><div><strong>목요일에 함께 나눠요</strong><p>모인 질문으로 답변과 강의를 준비합니다.</p></div></li></ol><div className="quiet"><Check size={16}/>단체 채팅 알림 없이, 편한 시간에.</div></section><div className="draft-note"><Sparkles size={16}/><p>AI는 질문의 핵심만 정리합니다.<br/>본문 해석과 답변은 인도자가 준비합니다.<br/><span>{"요약이 원래 질문과 다르면 원문을 기준으로 읽어주세요."}</span></p></div></aside></div><footer><AdminPanel/></footer></main>
 <dialog ref={dialog} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===dialog.current)close();}}><form onSubmit={submit} className="question-form"><div className="form-top"><span className="eyebrow">함께 나눌 궁금증</span><button type="button" className="icon-button" onClick={close} disabled={sending} aria-label="닫기"><X/></button></div><h2>질문 남기기</h2><p className="form-intro">로그인 없이 남길 수 있어요. 등록한 내용은 게시판에 공개됩니다.</p><label htmlFor="passage">성경 본문 <span>필수</span></label><input id="passage" autoFocus required maxLength={80} placeholder="예: 마태복음 5장 3절" value={passage} onChange={e=>setPassage(e.target.value)} disabled={sending}/><label htmlFor="content">궁금한 내용 <span>필수</span></label><textarea id="content" required minLength={5} maxLength={2000} rows={6} placeholder="읽으면서 궁금했던 점을 자유롭게 적어주세요." value={content} onChange={e=>setContent(e.target.value)} disabled={sending}/><div className="char-count">{content.length} / 2,000</div><label htmlFor="name">이름 <span>선택</span></label><input id="name" maxLength={30} placeholder="비워두면 ‘익명’으로 등록됩니다" value={name} onChange={e=>setName(e.target.value)} disabled={sending}/><p className="privacy-note">연락처 등 개인정보는 적지 말아주세요.{aiEnabled&&<> 질문 본문과 장·절은 핵심 요약을 위해 OpenAI에 전달됩니다.</>}<br/>성경통독과 무관한 게시글은 고지 없이 삭제될 수 있습니다.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary submit" disabled={sending}><Send size={18}/>{sending?"등록하고 있어요…":"질문 등록하기"}</button></form></dialog></>;
}


