"use client";
import {useRef,useState,type FormEvent} from 'react';
import {questionEndpoint} from '../lib/api-client';
type Q={id:string;passage:string;content:string;name:string};
export default function AdminPanel(){
 const dialog=useRef<HTMLDialogElement>(null);
 const [token,setToken]=useState(''),[password,setPassword]=useState(''),[items,setItems]=useState<Q[]>([]),[edit,setEdit]=useState<Q|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState<string|null>(null);
 const base=()=>questionEndpoint().replace(/\/questions$/,'/admin');
 async function refresh(){const r=await fetch(questionEndpoint());if(!r.ok)throw Error('질문을 불러오지 못했습니다.');setItems(((await r.json()) as {questions:Q[]}).questions);window.dispatchEvent(new Event('questions-updated'));}
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch(base()+'/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json() as {error?:string;token:string};if(!r.ok)throw Error(d.error);setToken(d.token);setPassword('');await refresh();}catch(e){setMessage(e instanceof Error?e.message:'연결 오류');}finally{setBusy(false);}}
 async function save(id:string,method:'PATCH'|'DELETE'){setBusy(true);setMessage('');try{const r=await fetch(base()+'/questions/'+id,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:method==='PATCH'?JSON.stringify(edit):undefined});const d=await r.json() as {error?:string;token:string};if(r.status===401)setToken('');if(!r.ok)throw Error(d.error);setEdit(null);setRemove(null);await refresh();setMessage(method==='PATCH'?'수정했습니다. 이전 AI 요약은 지우고 수정한 원문을 표시합니다.':'삭제했습니다.');}catch(e){setMessage(e instanceof Error?e.message:'연결 오류');}finally{setBusy(false);}}
 return <><button className="admin-entry" aria-label="관리자 로그인" onClick={()=>{setMessage('');dialog.current?.showModal();if(token)void refresh().catch(()=>setMessage('질문을 불러오지 못했습니다.'));}}>관리자</button><dialog ref={dialog} className="admin-dialog" onClick={e=>{if(e.target===e.currentTarget&&!busy)dialog.current?.close();}} onCancel={e=>{if(busy)e.preventDefault();}}><div className="question-form"><div className="form-top"><h2>{token?'질문 관리':'관리자 로그인'}</h2><button className="icon-button" disabled={busy} onClick={()=>dialog.current?.close()} aria-label="관리자 창 닫기">×</button></div>{message&&<p role="status">{message}</p>}{!token?<form onSubmit={login}><label htmlFor="admin-password">관리자 비밀번호</label><input id="admin-password" type="password" autoComplete="current-password" required maxLength={200} value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary submit" disabled={busy}>로그인</button></form>:<><p className="privacy-note">로그인은 1시간 동안 유지됩니다. 새로고침하면 다시 로그인합니다.</p><button className="admin-action" disabled={busy} onClick={()=>{setToken('');setItems([]);setEdit(null);setMessage('로그아웃했습니다.');}}>로그아웃</button>{!items.length&&<p>등록된 질문이 없습니다.</p>}{items.map(q=><section className="admin-question" key={q.id}>{edit?.id===q.id?<form onSubmit={e=>{e.preventDefault();void save(q.id,'PATCH');}}><label>성경 본문<input required maxLength={80} value={edit.passage} onChange={e=>setEdit({...edit,passage:e.target.value})}/></label><label>질문<textarea required minLength={5} maxLength={2000} value={edit.content} onChange={e=>setEdit({...edit,content:e.target.value})}/></label><label>이름<input maxLength={30} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><button className="admin-action" disabled={busy}>저장</button><button type="button" className="admin-action" disabled={busy} onClick={()=>setEdit(null)}>취소</button></form>:<><strong>{q.passage}</strong><p>{q.content}</p><small>{q.name}</small><div><button className="admin-action" disabled={busy} onClick={()=>{setEdit({...q});setRemove(null);}}>수정</button><button className="admin-action" disabled={busy} onClick={()=>setRemove(q.id)}>삭제</button></div>{remove===q.id&&<div role="alert"><p>이 질문을 게시판에서 삭제할까요?</p><button className="admin-action" disabled={busy} onClick={()=>void save(q.id,'DELETE')}>삭제 확인</button><button className="admin-action" disabled={busy} onClick={()=>setRemove(null)}>취소</button></div>}</>}</section>)}</>}</div></dialog></>;
}
